### ISSUE TITLE
update for react 0.59

### ISSUE THREAD

**Issue by malikdoksoz** [GeekyAnts/vue-native-cli#12]
```
- Creating react native app malik project
This will walk you through creating a new React Native project in C:\Users\sonsu\Desktop\VNforRN\malik
Using yarn v1.13.0
Installing react-native@0.58.1...
yarn add v1.13.0
```

Now 0.58.1 please update

**Comment by neeraj-singh47** [comment]
The latest version has been released to support react-native 0.59

**Comment by chars1205** [comment]
@neeraj-singh47 Does react-native 0.59.x support??

**Comment by neeraj-singh47** [comment]
@chars1205 You can update the react-native version manually. It should work fine

**Comment by chars1205** [comment]
@neeraj-singh47 
I am manually updating
Does react-native version is supported from 0.59.0 to 0.59.8?
