### ISSUE TITLE
vue-native-scripts missing in default install

### ISSUE THREAD

**Issue by Adohk** [GeekyAnts/vue-native-cli#17]
Using the default install `vue-native init <app>` installs fine but when running npm start, expo starts then throws the following error.

```
(node:6752) UnhandledPromiseRejectionWarning: Error: Cannot find module 'vue-native-scripts'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Ale\Vue\native\test\vueTransformerPlugin.js:2:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

It seems it doesn't install `vue-native-scripts` or `@babel/core@^7.0.0-0`.
`yarn add` can't find said version of babel core either.

So installing both and babel core at 7.0.0 then running on my phone threw another error:
`node_modules\expo\AppEntry.js: [BABEL] C:\User\Vue\native\test\node_modules\expo\AppEntry.js: Cannot find module '@babel/plugin-proposal-decorators'`

After installing everything and running my app it displays the contents of App.js instead of App.vue, removing app.js solved that though.

using vue-native-cli 0.0.7

**Comment by Adohk** [comment]
Package.json it generated:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^33.0.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-web": "^0.11.4",
    "vue-native-core": "0.0.8",
    "vue-native-helper": "0.0.11"
  },
  "devDependencies": {
    "@babel/core": "7.0.0",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "babel-preset-expo": "^5.1.1",
    "vue-native-scripts": "0.0.16"
  },
  "private": true
}

```

**Comment by RishabhKarnad** [comment]
@Adohk please let us know if you are experiencing the same issue with CLI v0.1.0

**Comment by khalid14** [comment]
Hey @RishabhKarnad , I am having the same issue "Error: Cannot find module 'vue-native-scripts'" - When i installed the package first it shows native-scripts folder inside package manager but after a second it removes that.

**Comment by yitelee** [comment]
using cli v.0.1.0 to init a new project, failed in last step
`npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\leno\\AppData\\R
oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "vue-native-scripts"
"@babel/core@7.0.0-0" "--save-dev"`
..................
`npm ERR! notarget No compatible version found: @babel/core@7.0.0-0
npm ERR! notarget Valid install targets:
npm ERR! notarget 7.5.5, 7.5.4, 7.5.0, 7.4.5, 7.4.4, 7.4.3, 7.4.0, 7.3.4, 7.3.3,
 7.2.2, 7.2.0, 7.1.6, 7.1.5, 7.1.2, 7.1.1, 7.1.0, 7.0.1, 7.0.0, 7.0.0-rc.4, 7.0.
0-rc.3, 7.0.0-rc.2, 7.0.0-rc.1, 7.0.0-rc.0, 7.0.0-beta.56, 7.0.0-beta.55, 7.0.0-
beta.54, 7.0.0-beta.53, 7.0.0-beta.52, 7.0.0-beta.51, 7.0.0-beta.50, 7.0.0-beta.
49, 7.0.0-beta.48, 7.0.0-beta.47, 7.0.0-beta.46, 7.0.0-beta.45, 7.0.0-beta.44, 7
.0.0-beta.43, 7.0.0-beta.42, 7.0.0-beta.41, 7.0.0-beta.40, 7.0.0-beta.39, 7.0.0-
beta.38, 7.0.0-beta.37, 7.0.0-beta.36, 7.0.0-beta.35, 7.0.0-beta.34, 7.0.0-beta.
33, 7.0.0-beta.32, 7.0.0-beta.31, 7.0.0-beta.5, 7.0.0-beta.4, 6.0.0-bridge.1`

so I have to manually install the missing package
> cd app
>npm i --save @babel/core@7.0.0
>npm i --save vue-native-scripts

**Comment by gabeesms** [comment]
eu tentei fazer executando o comando npm install vue-native-scripts --save-dev
e depois npm start e funcionou.

**Comment by Hol7** [comment]
This is what i'm facing , i do need some Help

(node:9023) UnhandledPromiseRejectionWarning: Error: Cannot find module 'vue-native-scripts'
Require stack:

    /home/talent/demo/vueTransformerPlugin.js
    /home/talent/demo/node_modules/metro/src/JSTransformer/worker.js
    /home/talent/demo/node_modules/metro/src/DeltaBundler/Transformer/getTransformCacheKey.js
    /home/talent/demo/node_modules/metro/src/DeltaBundler/Transformer.js
    /home/talent/demo/node_modules/metro/src/Bundler.js
    /home/talent/demo/node_modules/metro/src/IncrementalBundler.js
    /home/talent/demo/node_modules/metro/src/index.js
    /home/talent/demo/node_modules/@react-native-community/cli/build/tools/loadMetroConfig.js
    /home/talent/demo/node_modules/@react-native-community/cli/build/commands/server/runServer.js
    /home/talent/demo/node_modules/@react-native-community/cli/build/commands/server/server.js
    /home/talent/demo/node_modules/@react-native-community/cli/build/commands/index.js
    /home/talent/demo/node_modules/@react-native-community/cli/build/cliEntry.js
    /home/talent/demo/node_modules/@react-native-community/cli/build/index.js
    /home/talent/demo/node_modules/react-native/local-cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object. (/home/talent/demo/vueTransformerPlugin.js:2:24)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    (node:9023) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    (node:9023) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ondast** [comment]
This issue remains for me on windows 10, node version: v12.16.1, npm version: 6.14.2. It seems the last install step of init a new project fails 

> Installing Vue Native devDependencies
> 'yarn' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @babel/core@7.0.0-0.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> 
> npm ERR! A complete log of this run can be found in:
> √ Installed Vue Native devDependencies
> 

I resolved it by installing the missing packages:

> npm i --save @babel/core@7.0.0
> npm i --save vue-native-scripts

**Comment by toitoi** [comment]
same issue as @ondast , below script fix that,
npm i --save @babel/core@7.0.0
npm i --save vue-native-scripts
