### ISSUE TITLE
Please globally install create-react-native-app dependency

### ISSUE THREAD

**Issue by rodrigorioo** [GeekyAnts/vue-native-cli#20]
Hi, I follow all the instructions and follow steps in other issues report and still give me this error. I have all globaly installed and I can't init the project

**Comment by RishabhKarnad** [comment]
Hi @rodrigorioo. Please provide the following information:
- What OS are you using?
- What is the output of `expo --version`
- What is the output of `vue-native --version`

**Comment by rodrigorioo** [comment]
Hi @RishabhKarnad thanks for the reply! I found a solution for the problem.

When I write "expo --version" this tell me that Node.js v9 is not supported, so I update to v10 and now works!

Thank you!
