### ISSUE TITLE
New project does not run

### ISSUE THREAD

**Issue by ChildishForces** [GeekyAnts/vue-native-cli#23]
Receiving the following error:

```
Unable to resolve "../../App" from "node_modules/expo/AppEntry.js"
Failed building JavaScript bundle.
```

**Comment by RishabhKarnad** [comment]
Hi @ChildishForces.

Just for some more info, could you share the following with us?
- The contents of your package.json
- Did this happen with a freshly generated project (without any changes)?
- The contents of the project directory at the top level (e.g. the result of `ls`)

**Comment by mikkah** [comment]
Hi  @RishabhKarnad I'm facing the same error as stated by @ChildishForces

Content of package.json

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^34.0.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-web": "^0.11.4",
    "vue-native-core": "0.1.0",
    "vue-native-helper": "0.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-0",
    "babel-preset-expo": "^6.0.0",
    "vue-native-scripts": "0.1.0"
  },
  "private": true
}


This is a freshly generated project without any changes

**Comment by ChildishForces** [comment]
I'm identical to @mikkah's.

**Comment by ChildishForces** [comment]
Unfortunately this makes Vue Native unusable for me atm. :(

**Comment by Syltis** [comment]
There seems to be a bundle of proposed solutions out there for this, but none has been working in my case.

**Comment by Syltis** [comment]
There is a solution, see https://github.com/GeekyAnts/vue-native-core/issues/183

**Comment by RishabhKarnad** [comment]
As mentioned in https://github.com/GeekyAnts/vue-native-core/issues/183, the crash is caused by an issue in Expo

After making a new project, changes will be required in the `app.json` for the project to work.

The README.md will be updated to reflect this

**Comment by ChildishForces** [comment]
Not sure this is the best solution. Surely vue-native-cli should be generating with this solution, rather than a note in the readme, as what is the point in the CLI if not to scaffold a working Vue Native app?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RishabhKarnad** [comment]
@ChildishForces I have created a PR #26 to address this. It should roll out with the next release.

**Comment by ChildishForces** [comment]
Awesome, much obliged!
