### ISSUE TITLE
web view components not working 

### ISSUE THREAD

**Issue by imsidz** [GeekyAnts/vue-native-cli#28]
i have just new init with ```vue-native init <projectName>``` and trying to make webview but something went wrong

with your [documentation ](https://vue-native.io/docs/basic-components.html#WebView)
i am using simply

```
<template>
    <web-view
        :source="{uri: 'https://fhirtmis.online'}"
        :style="{marginTop: 20}"
    />
</template>
```
but getting components not found

**Comment by RohanTalip** [comment]
WebView is no longer available from Vue Native:
https://github.com/GeekyAnts/vue-native-core#react-native-components-that-cant-be-used-out-of-the-box

The documentation is on vue-native.io relating to WebView out of date.

You can import it from `react-native-webview` instead:
https://github.com/react-native-community/react-native-webview

**Comment by RishabhKarnad** [comment]
The documentation will be updated soon. Closing this issue since it's not really related to `vue-native-cli`. Feel free to create an issue for this in `vue-native-website`

**Comment by vommaroitiscardano** [comment]
It's not available yet?

**Comment by vommaroitiscardano** [comment]
> The documentation will be updated soon. Closing this issue since it's not really related to `vue-native-cli`. Feel free to create an issue for this in `vue-native-website`

I see the documentation and there is the web-view right now. But it doesn't work!
