### ISSUE TITLE
App.js and App.vue are both present in projects created freshly on Windows

### ISSUE THREAD

**Issue by RishabhKarnad** [GeekyAnts/vue-native-cli#29]
On creating a new project with
```
vue-native init <projectName>
```
the generated project directory contains both an `App.js` file as well as an `App.vue` file.

#### Expected behaviour

On running the above command, a project directory containing the following structure should be created
```
<projectName>
  |_ .expo-shared/
  |_ .git/
  |_ assets/
  |_ node_modules/
  |_ .gitignore
  |_ .watchmanconfig
  |_ app.json
  |_ App.vue
  |_ babel.config.js
  |_ metro.config.js
  |_ package.json
  |_ vueTransformerPlugin.js
  |_ yarn.lock
```

On running
```
npm start
```
the contents of the `App.vue` file should be rendered in the simulator.

#### Observed behaviour

On Windows, after creation, the project directory also contains an `App.js` file. On starting the project, the contents of this file are rendered instead and the `App.vue` file is ignored.

#### Vue Naitve CLI version used

v0.1.1

**Comment by RishabhKarnad** [comment]
The issue is described [here](https://github.com/GeekyAnts/vue-native-core/issues/205) by @YannickSilva

This screenshot of the generated directory was provided there

![64984735-4f27c080-d8bb-11e9-9884-ff240a15abfb](https://user-images.githubusercontent.com/30865239/65071852-40213b00-d9ad-11e9-8960-12de1b22007c.png)

**Comment by jonnycraze** [comment]
I'm experiencing the same issue, what is the ETA on a release fix, or is there a work around in the mean time?

**Comment by orelinde** [comment]
Hi @jonnycraze I got it working by:
1. Remove 
`App.js`
2. Execute:
`npm install vue-native-scripts --save-dev`
`npm install vue-native-core vue-native-helper --save`
`npm install`
3. Run as normal: 
`react-native run-android`

**Comment by tjharrisonuk** [comment]
Didn't work for me.

**Comment by karoletrych** [comment]
Doesn't work for me either.

**Comment by bbalkonsky** [comment]
and for me

**Comment by kothanzaw** [comment]
also not working for me
