### ISSUE TITLE
Error creating project

### ISSUE THREAD

**Issue by JeRabix** [GeekyAnts/vue-native-cli#31]
When I execute the vue-native init command, if the name of my application has the symbol "_" then the application is created using react cli and not expo cli. But if you write down the name of the project in one word or through "-" then everything is fine.

**Comment by RishabhKarnad** [comment]
This is intended. The CLI will first display that it is not a valid project name for Expo based projects. On continuing (saying yes to continue with invalid name), the CLI attempts to make a project with react-native-cli.
