### ISSUE TITLE
Invalid regular expression when doing --no-expo installation

### ISSUE THREAD

**Issue by BHuys** [GeekyAnts/vue-native-cli#39]
When I try to run the application with 'npm run start' after going through the installation tutorial I get an error.

`error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.0.1 start script.`

**Comment by RishabhKarnad** [comment]
@BHuys could you please provide
- info on the platform? (OS, shell, target device)
- generated package.json
- generated directory structure

**Comment by RishabhKarnad** [comment]
You might find the solution here:
https://stackoverflow.com/questions/58268958/i-am-getting-invalid-regular-expression-error-while-running-npm-start
