### ISSUE TITLE
Question: I have installed vue native, i haven't installed emulator so im opening the app in browser. The problem is that the system is running App.js file but not App.vue. How can i sort out this? Thanks

### ISSUE THREAD

**Issue by Sarmad-Akram** [GeekyAnts/vue-native-cli#40]
The best place to find answers is the [documentation](https://www.vue-native.io/docs/installation.html)  📖

If you still haven't found what you are looking for or need more help, feel free to reach out on [Vue Native Slack](http://slack.vue-native.io/)

**Comment by RishabhKarnad** [comment]
Seems to be a duplicate of #29
