### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by emrecanmuslu** [GeekyAnts/vue-native-cli#43]
Hi,
I can run the react native project that I created, but when I want to run the vue native project I just created on android, I get this error;
https://prnt.sc/wm36uu

**Comment by RishabhKarnad** [comment]
This looks like an issue with Android Studio tools not being correctly included on $PATH

**Comment by RishabhKarnad** [comment]
Please try with [v0.2.0](https://github.com/GeekyAnts/vue-native-cli/releases/tag/v0.2.0) and ensure that the Android development tools are added to your path variable.
https://stackoverflow.com/a/43626724
https://github.com/facebook/react-native/issues/29147

Please reopen if the issue persists
