### ISSUE TITLE
Transform Error Running Demo

### ISSUE THREAD

**Issue by angelhdzmultimedia** [GeekyAnts/vue-native-cli#46]
I'm getting a transform error trying to run the demo vue native app. I tried installing **metro-react-native-babel-transform** package, because it was missing from devDependencies in the package.json, but that doesn't fix it. Also tried previous version of both **metro-react-native-babel-transform** and **metro-react-native-babel-preset** (0.64.0). This issue is only happening in Vue Native app. If I create a React Native demo app it works on my Android emulator perfectly.

![image](https://user-images.githubusercontent.com/10191085/110122893-9ac37800-7d96-11eb-9e41-906231096b36.png)

![image](https://user-images.githubusercontent.com/10191085/110122925-a57e0d00-7d96-11eb-9a88-6adaa8caa1cd.png)

**Comment by RishabhKarnad** [comment]
@angelhdz This should be fixed now. vue-native-cli must have created a project with vue-native-core@0.3.0-rc.1 which has this issue
https://github.com/GeekyAnts/vue-native-core/issues/302

Please use these instructions in case you want to continue to use the project you had created:
https://github.com/GeekyAnts/vue-native-core/issues/304#issuecomment-796659899

Alternatively, you can create a new project with vue-native-cli, which will now correctly use vue-native-core@0.2.0
