### ISSUE TITLE
Fresh install does not work without Yarn

### ISSUE THREAD

**Issue by trajano** [GeekyAnts/vue-native-cli#50]
**Description of the bug**
I followed the guide in https://vue-native.io/docs/installation.html#For-Expo-users

**To Reproduce**
1. `vue-native init learn-vn`
2. `cd learn-vn`
3. `npm start`
4. Scan QR code (though the error occurs before)

**What I expected**
App to appear on expo

**Screenshots**
![image](https://user-images.githubusercontent.com/110627/125616685-34223e99-fb96-4c3b-b061-b52ee23c6e91.png)

**Did I use `vue-native-cli` to create the project?**
Yes

**Am I using Expo?**
Yes
- If you created your project with `vue-native init <projectName>` then yes
- If you used `vue-native init <projectName> --no-expo`, then no

**Development platform (please complete the following information):**
 - OS: Windows 10
 - Shell/terminal:: git bash
 - no Yarn

❯ expo --version
4.7.3

❯ npm --version
6.14.4

❯ node --version
v12.18.0

**The device on which I run my Vue Native app**
 - Device: iPhone SE 2020
 - OS: iOS 14

**Comment by trajano** [comment]
Will this be released soon

**Comment by RishabhKarnad** [comment]
This has been released with [v0.3.0](https://github.com/GeekyAnts/vue-native-cli/releases/tag/v0.3.0)

You can also manually edit the file in an existing project to fix the error
