### ISSUE TITLE
Use expo-cli instead of crna

### ISSUE THREAD

**Issue by syropian** [GeekyAnts/vue-native-cli#6]
[CRNA](https://github.com/react-community/create-react-native-app) has been deprecated in favour of [Expo CLI](https://github.com/expo/expo-cli). expo-cli includes the `create-react-native-app` command for backwards compatibility, so I thought vue-native-cli might still work, but unfortunately I'm getting the error `Please globally install create-react-native-app dependency` even though I did install the `expo-cli` tool globally.

**Comment by OmarAbdo** [comment]
Have you solved this? I'm facing the same problem too

**Comment by syropian** [comment]
@OmarAbdo Unfortunately not, I've moved on to NativeScript-Vue as it seems a little more active/well-supported.

**Comment by neeraj-singh47** [comment]
Issue has been fixed https://github.com/GeekyAnts/vue-native-cli/commit/340854e58cf12e50fcfb9cf872b9bb1f3c9d9958
