### ISSUE TITLE
NPM Start always ask me to install Expo CLI while I already have installed in globally

### ISSUE THREAD

**Issue by OmarAbdo** [GeekyAnts/vue-native-cli#8]
-npm start

=This command requires Expo CLI.
=Do you want to install it globally [Y/n]?

**Comment by neeraj-singh47** [comment]
Issue has been fixed https://github.com/GeekyAnts/vue-native-cli/commit/340854e58cf12e50fcfb9cf872b9bb1f3c9d9958
